### ISSUE TITLE
The QR code for sign-in appears to be loading depending on the screen width.

### ISSUE THREAD

**Issue by erados** [worldcoin/world-id-sign-in#88]
I'm not sure if this is an intended feature, but it clearly affects usability negatively, so I'm reporting it.

For example, when splitting the screen to test the app, the QR code often doesn't appear, causing inconvenience.

Please refer to the video below.

https://github.com/worldcoin/world-id-sign-in/assets/19205043/92ff9747-3c9e-4427-8ce0-1933207361fb

**Comment by andy-t-wang** [comment]
This issue has been fixed!
